# Generated by Django 4.1.7 on 2023-03-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Instructor', models.CharField(max_length=255)),
                ('SeatData', models.CharField(max_length=255)),
                ('Rooms', models.CharField(max_length=255)),
                ('Times', models.CharField(max_length=255)),
            ],
        ),
    ]
