# Generated by Django 4.1.7 on 2023-03-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_account_admin_instructor_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='GradedInMeeting',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='OfficeHours',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='WithDiscussion',
            field=models.BooleanField(null=True),
        ),
    ]
