# Generated by Django 4.1.7 on 2023-04-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_alter_course_gradedinmeeting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='positions',
            new_name='position',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=255)),
                ('Experience', models.CharField(max_length=2056)),
                ('Resume', models.FileField(blank=True, default='', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.account')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Applications',
            field=models.ManyToManyField(blank=True, default='', to='summary.application'),
        ),
    ]
