# Generated by Django 4.1.7 on 2023-04-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_rename_positions_admin_position_application_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='CourseName',
            new_name='SelectedCourse',
        ),
        migrations.AlterField(
            model_name='application',
            name='Experience',
            field=models.CharField(max_length=4096),
        ),
    ]
