# Generated by Django 4.1.7 on 2023-03-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="TAs",
            field=models.CharField(default=0, max_length=8),
        ),
    ]
