# Generated by Django 4.1.7 on 2023-03-21 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_course_description_course_extrainfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('bcemail', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('permissions', models.CharField(choices=[('STUDENT', 'Student'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Admin')], default='Student', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='summary.account')),
                ('positions', models.CharField(max_length=255)),
            ],
            bases=('summary.account',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='summary.account')),
                ('position', models.CharField(max_length=255)),
            ],
            bases=('summary.account',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='summary.account')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='Freshman', max_length=2)),
                ('major', models.CharField(max_length=64)),
                ('eagleid', models.CharField(max_length=16)),
                ('work', models.CharField(choices=[('YES', 'Open to work'), ('NO', 'Not open to work')], default='NO', max_length=16)),
            ],
            bases=('summary.account',),
        ),
    ]
