# Generated by Django 4.1.7 on 2023-05-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='GradedInMeeting',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='WithDiscussion',
            field=models.BooleanField(),
        ),
    ]
