# Generated by Django 4.1.7 on 2023-05-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_alter_course_gradedinmeeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='OfficeHours',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
